// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package linuxdrm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type linuxdrmInflightIoctl struct {
	_       structs.HostLayout
	Fd      int32
	Pad0    uint32
	Command uint64
	StartNs uint64
}

// loadLinuxdrm returns the embedded CollectionSpec for linuxdrm.
func loadLinuxdrm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_LinuxdrmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load linuxdrm: %w", err)
	}

	return spec, err
}

// loadLinuxdrmObjects loads linuxdrm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*linuxdrmObjects
//	*linuxdrmPrograms
//	*linuxdrmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadLinuxdrmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadLinuxdrm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// linuxdrmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type linuxdrmSpecs struct {
	linuxdrmProgramSpecs
	linuxdrmMapSpecs
	linuxdrmVariableSpecs
}

// linuxdrmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type linuxdrmProgramSpecs struct {
	HandleEnterIoctl     *ebpf.ProgramSpec `ebpf:"handle_enter_ioctl"`
	HandleExitIoctl      *ebpf.ProgramSpec `ebpf:"handle_exit_ioctl"`
	HandleSchedSwitch    *ebpf.ProgramSpec `ebpf:"handle_sched_switch"`
	HandleSchedWakeup    *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup"`
	HandleSchedWakeupNew *ebpf.ProgramSpec `ebpf:"handle_sched_wakeup_new"`
}

// linuxdrmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type linuxdrmMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	Inflight *ebpf.MapSpec `ebpf:"inflight"`
	WakeupTs *ebpf.MapSpec `ebpf:"wakeup_ts"`
}

// linuxdrmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type linuxdrmVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// linuxdrmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadLinuxdrmObjects or ebpf.CollectionSpec.LoadAndAssign.
type linuxdrmObjects struct {
	linuxdrmPrograms
	linuxdrmMaps
	linuxdrmVariables
}

func (o *linuxdrmObjects) Close() error {
	return _LinuxdrmClose(
		&o.linuxdrmPrograms,
		&o.linuxdrmMaps,
	)
}

// linuxdrmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadLinuxdrmObjects or ebpf.CollectionSpec.LoadAndAssign.
type linuxdrmMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	Inflight *ebpf.Map `ebpf:"inflight"`
	WakeupTs *ebpf.Map `ebpf:"wakeup_ts"`
}

func (m *linuxdrmMaps) Close() error {
	return _LinuxdrmClose(
		m.Events,
		m.Inflight,
		m.WakeupTs,
	)
}

// linuxdrmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadLinuxdrmObjects or ebpf.CollectionSpec.LoadAndAssign.
type linuxdrmVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// linuxdrmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadLinuxdrmObjects or ebpf.CollectionSpec.LoadAndAssign.
type linuxdrmPrograms struct {
	HandleEnterIoctl     *ebpf.Program `ebpf:"handle_enter_ioctl"`
	HandleExitIoctl      *ebpf.Program `ebpf:"handle_exit_ioctl"`
	HandleSchedSwitch    *ebpf.Program `ebpf:"handle_sched_switch"`
	HandleSchedWakeup    *ebpf.Program `ebpf:"handle_sched_wakeup"`
	HandleSchedWakeupNew *ebpf.Program `ebpf:"handle_sched_wakeup_new"`
}

func (p *linuxdrmPrograms) Close() error {
	return _LinuxdrmClose(
		p.HandleEnterIoctl,
		p.HandleExitIoctl,
		p.HandleSchedSwitch,
		p.HandleSchedWakeup,
		p.HandleSchedWakeupNew,
	)
}

func _LinuxdrmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed linuxdrm_x86_bpfel.o
var _LinuxdrmBytes []byte
