// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package pyunwind

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type pywalkPyFrameWindow struct {
	_ structs.HostLayout
	B [96]uint8
}

type pywalkPyProcInfo struct {
	_                        structs.HostLayout
	NoneAddr                 uint64
	TssKey                   uint32
	PthreadSpecific1stblock  uint32
	PthreadKeyDataSize       uint32
	PthreadKeyDataOff        uint32
	PthreadSize              uint32
	FramePrevious            uint16
	FrameExecutable          uint16
	FrameInstrPtr            uint16
	FrameOwner               uint16
	ThreadstateFrame         uint16
	CodeArgcount             uint16
	CodeKwonlyargcount       uint16
	CodeFlags                uint16
	CodeFirstlineno          uint16
	FrameOwnerMax            uint8
	FrameOwnerCstack         uint8
	FrameOwnerBoundary       uint8
	FrameExecutableTagged    uint8
	ThreadstateFrameIndirect uint8
	Enabled                  uint8
	Pad                      [4]uint8
}

type pywalkSampleRecord struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		Pid         uint32
		Tid         uint32
		TimeNs      uint64
		Value       uint64
		Mode        uint8
		N_pcs       uint8
		WalkerFlags uint8
		Pad         uint8
		Pad2        uint32
		KernStack   int64
	}
	Pcs  [127]uint64
	Tags [127]uint8
	_    [1]byte
}

type pywalkWalkPersist struct {
	_               structs.HostLayout
	Pc              uint64
	Fp              uint64
	Sp              uint64
	InterpScratch   [4]uint64
	Pid             uint32
	Tid             uint32
	N_pcs           uint32
	PendingUnwinder uint32
	InterpDone      uint32
	Stopped         uint8
	Pad2            [3]uint8
	TailCalls       uint32
	Pad             uint32
}

// loadPywalk returns the embedded CollectionSpec for pywalk.
func loadPywalk() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PywalkBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load pywalk: %w", err)
	}

	return spec, err
}

// loadPywalkObjects loads pywalk and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*pywalkObjects
//	*pywalkPrograms
//	*pywalkMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPywalkObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPywalk()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// pywalkSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pywalkSpecs struct {
	pywalkProgramSpecs
	pywalkMapSpecs
	pywalkVariableSpecs
}

// pywalkProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pywalkProgramSpecs struct {
	InterpPythonPerfEvent   *ebpf.ProgramSpec `ebpf:"interp_python_perf_event"`
	InterpPythonSchedSwitch *ebpf.ProgramSpec `ebpf:"interp_python_sched_switch"`
	InterpPythonUprobe      *ebpf.ProgramSpec `ebpf:"interp_python_uprobe"`
}

// pywalkMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pywalkMapSpecs struct {
	InterpProgs    *ebpf.MapSpec `ebpf:"interp_progs"`
	InterpStats    *ebpf.MapSpec `ebpf:"interp_stats"`
	PyFrameScratch *ebpf.MapSpec `ebpf:"py_frame_scratch"`
	PyProcs        *ebpf.MapSpec `ebpf:"py_procs"`
	PyWalkCounters *ebpf.MapSpec `ebpf:"py_walk_counters"`
	WalkStates     *ebpf.MapSpec `ebpf:"walk_states"`
	WalkerScratch  *ebpf.MapSpec `ebpf:"walker_scratch"`
}

// pywalkVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type pywalkVariableSpecs struct {
}

// pywalkObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPywalkObjects or ebpf.CollectionSpec.LoadAndAssign.
type pywalkObjects struct {
	pywalkPrograms
	pywalkMaps
	pywalkVariables
}

func (o *pywalkObjects) Close() error {
	return _PywalkClose(
		&o.pywalkPrograms,
		&o.pywalkMaps,
	)
}

// pywalkMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPywalkObjects or ebpf.CollectionSpec.LoadAndAssign.
type pywalkMaps struct {
	InterpProgs    *ebpf.Map `ebpf:"interp_progs"`
	InterpStats    *ebpf.Map `ebpf:"interp_stats"`
	PyFrameScratch *ebpf.Map `ebpf:"py_frame_scratch"`
	PyProcs        *ebpf.Map `ebpf:"py_procs"`
	PyWalkCounters *ebpf.Map `ebpf:"py_walk_counters"`
	WalkStates     *ebpf.Map `ebpf:"walk_states"`
	WalkerScratch  *ebpf.Map `ebpf:"walker_scratch"`
}

func (m *pywalkMaps) Close() error {
	return _PywalkClose(
		m.InterpProgs,
		m.InterpStats,
		m.PyFrameScratch,
		m.PyProcs,
		m.PyWalkCounters,
		m.WalkStates,
		m.WalkerScratch,
	)
}

// pywalkVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPywalkObjects or ebpf.CollectionSpec.LoadAndAssign.
type pywalkVariables struct {
}

// pywalkPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPywalkObjects or ebpf.CollectionSpec.LoadAndAssign.
type pywalkPrograms struct {
	InterpPythonPerfEvent   *ebpf.Program `ebpf:"interp_python_perf_event"`
	InterpPythonSchedSwitch *ebpf.Program `ebpf:"interp_python_sched_switch"`
	InterpPythonUprobe      *ebpf.Program `ebpf:"interp_python_uprobe"`
}

func (p *pywalkPrograms) Close() error {
	return _PywalkClose(
		p.InterpPythonPerfEvent,
		p.InterpPythonSchedSwitch,
		p.InterpPythonUprobe,
	)
}

func _PywalkClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed pywalk_arm64_bpfel.o
var _PywalkBytes []byte
