// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package profile

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type offcpu_dwarfCfiEntry struct {
	_          structs.HostLayout
	PcStart    uint64
	PcEndDelta uint32
	CfaType    uint8
	FpType     uint8
	CfaOffset  int16
	FpOffset   int16
	RaOffset   int16
	RaType     uint8
	Pad        [5]uint8
	_          [6]byte
}

type offcpu_dwarfClassification struct {
	_          structs.HostLayout
	PcStart    uint64
	PcEndDelta uint32
	Mode       uint8
	Pad        [3]uint8
}

type offcpu_dwarfOffcpuStartKey struct {
	_    structs.HostLayout
	Pid  uint32
	Tgid uint32
}

type offcpu_dwarfPidConfig struct {
	_             structs.HostLayout
	Type          uint8
	CollectUser   uint8
	CollectKernel uint8
}

type offcpu_dwarfPidMapping struct {
	_        structs.HostLayout
	VmaStart uint64
	VmaEnd   uint64
	LoadBias uint64
	TableId  uint64
}

type offcpu_dwarfSampleRecord struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		Pid         uint32
		Tid         uint32
		TimeNs      uint64
		Value       uint64
		Mode        uint8
		N_pcs       uint8
		WalkerFlags uint8
		Pad         uint8
		Pad2        uint32
	}
	Pcs [127]uint64
}

// loadOffcpu_dwarf returns the embedded CollectionSpec for offcpu_dwarf.
func loadOffcpu_dwarf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Offcpu_dwarfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load offcpu_dwarf: %w", err)
	}

	return spec, err
}

// loadOffcpu_dwarfObjects loads offcpu_dwarf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*offcpu_dwarfObjects
//	*offcpu_dwarfPrograms
//	*offcpu_dwarfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOffcpu_dwarfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOffcpu_dwarf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// offcpu_dwarfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpu_dwarfSpecs struct {
	offcpu_dwarfProgramSpecs
	offcpu_dwarfMapSpecs
	offcpu_dwarfVariableSpecs
}

// offcpu_dwarfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpu_dwarfProgramSpecs struct {
	OffcpuDwarfSchedSwitch *ebpf.ProgramSpec `ebpf:"offcpu_dwarf_sched_switch"`
}

// offcpu_dwarfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpu_dwarfMapSpecs struct {
	CfiClassification        *ebpf.MapSpec `ebpf:"cfi_classification"`
	CfiClassificationLengths *ebpf.MapSpec `ebpf:"cfi_classification_lengths"`
	CfiLengths               *ebpf.MapSpec `ebpf:"cfi_lengths"`
	CfiRules                 *ebpf.MapSpec `ebpf:"cfi_rules"`
	OffcpuStart              *ebpf.MapSpec `ebpf:"offcpu_start"`
	PidMappingLengths        *ebpf.MapSpec `ebpf:"pid_mapping_lengths"`
	PidMappings              *ebpf.MapSpec `ebpf:"pid_mappings"`
	Pids                     *ebpf.MapSpec `ebpf:"pids"`
	StackEvents              *ebpf.MapSpec `ebpf:"stack_events"`
	WalkerScratch            *ebpf.MapSpec `ebpf:"walker_scratch"`
}

// offcpu_dwarfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpu_dwarfVariableSpecs struct {
	BtfAnchorCfiEntry       *ebpf.VariableSpec `ebpf:"_btf_anchor_cfi_entry"`
	BtfAnchorClassification *ebpf.VariableSpec `ebpf:"_btf_anchor_classification"`
	BtfAnchorOffcpuStartKey *ebpf.VariableSpec `ebpf:"_btf_anchor_offcpu_start_key"`
	BtfAnchorPidMapping     *ebpf.VariableSpec `ebpf:"_btf_anchor_pid_mapping"`
}

// offcpu_dwarfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOffcpu_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpu_dwarfObjects struct {
	offcpu_dwarfPrograms
	offcpu_dwarfMaps
	offcpu_dwarfVariables
}

func (o *offcpu_dwarfObjects) Close() error {
	return _Offcpu_dwarfClose(
		&o.offcpu_dwarfPrograms,
		&o.offcpu_dwarfMaps,
	)
}

// offcpu_dwarfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOffcpu_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpu_dwarfMaps struct {
	CfiClassification        *ebpf.Map `ebpf:"cfi_classification"`
	CfiClassificationLengths *ebpf.Map `ebpf:"cfi_classification_lengths"`
	CfiLengths               *ebpf.Map `ebpf:"cfi_lengths"`
	CfiRules                 *ebpf.Map `ebpf:"cfi_rules"`
	OffcpuStart              *ebpf.Map `ebpf:"offcpu_start"`
	PidMappingLengths        *ebpf.Map `ebpf:"pid_mapping_lengths"`
	PidMappings              *ebpf.Map `ebpf:"pid_mappings"`
	Pids                     *ebpf.Map `ebpf:"pids"`
	StackEvents              *ebpf.Map `ebpf:"stack_events"`
	WalkerScratch            *ebpf.Map `ebpf:"walker_scratch"`
}

func (m *offcpu_dwarfMaps) Close() error {
	return _Offcpu_dwarfClose(
		m.CfiClassification,
		m.CfiClassificationLengths,
		m.CfiLengths,
		m.CfiRules,
		m.OffcpuStart,
		m.PidMappingLengths,
		m.PidMappings,
		m.Pids,
		m.StackEvents,
		m.WalkerScratch,
	)
}

// offcpu_dwarfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadOffcpu_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpu_dwarfVariables struct {
	BtfAnchorCfiEntry       *ebpf.Variable `ebpf:"_btf_anchor_cfi_entry"`
	BtfAnchorClassification *ebpf.Variable `ebpf:"_btf_anchor_classification"`
	BtfAnchorOffcpuStartKey *ebpf.Variable `ebpf:"_btf_anchor_offcpu_start_key"`
	BtfAnchorPidMapping     *ebpf.Variable `ebpf:"_btf_anchor_pid_mapping"`
}

// offcpu_dwarfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOffcpu_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpu_dwarfPrograms struct {
	OffcpuDwarfSchedSwitch *ebpf.Program `ebpf:"offcpu_dwarf_sched_switch"`
}

func (p *offcpu_dwarfPrograms) Close() error {
	return _Offcpu_dwarfClose(
		p.OffcpuDwarfSchedSwitch,
	)
}

func _Offcpu_dwarfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed offcpu_dwarf_x86_bpfel.o
var _Offcpu_dwarfBytes []byte
