// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package profile

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type perfPidConfig struct {
	Type          uint8
	CollectUser   uint8
	CollectKernel uint8
}

type perfSampleKey struct {
	Pid       uint32
	Flags     uint32
	KernStack int64
	UserStack int64
}

// loadPerf returns the embedded CollectionSpec for perf.
func loadPerf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_PerfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load perf: %w", err)
	}

	return spec, err
}

// loadPerfObjects loads perf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*perfObjects
//	*perfPrograms
//	*perfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPerfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPerf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// perfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perfSpecs struct {
	perfProgramSpecs
	perfMapSpecs
}

// perfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perfProgramSpecs struct {
	Profile *ebpf.ProgramSpec `ebpf:"profile"`
}

// perfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perfMapSpecs struct {
	Counts   *ebpf.MapSpec `ebpf:"counts"`
	Pids     *ebpf.MapSpec `ebpf:"pids"`
	Stackmap *ebpf.MapSpec `ebpf:"stackmap"`
}

// perfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPerfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perfObjects struct {
	perfPrograms
	perfMaps
}

func (o *perfObjects) Close() error {
	return _PerfClose(
		&o.perfPrograms,
		&o.perfMaps,
	)
}

// perfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPerfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perfMaps struct {
	Counts   *ebpf.Map `ebpf:"counts"`
	Pids     *ebpf.Map `ebpf:"pids"`
	Stackmap *ebpf.Map `ebpf:"stackmap"`
}

func (m *perfMaps) Close() error {
	return _PerfClose(
		m.Counts,
		m.Pids,
		m.Stackmap,
	)
}

// perfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPerfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perfPrograms struct {
	Profile *ebpf.Program `ebpf:"profile"`
}

func (p *perfPrograms) Close() error {
	return _PerfClose(
		p.Profile,
	)
}

func _PerfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perf_arm64_bpfel.o
var _PerfBytes []byte
