// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package profile

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type perf_dwarfPidConfig struct {
	_             structs.HostLayout
	Type          uint8
	CollectUser   uint8
	CollectKernel uint8
}

type perf_dwarfSampleRecord struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		Pid         uint32
		Tid         uint32
		TimeNs      uint64
		Value       uint64
		Mode        uint8
		N_pcs       uint8
		WalkerFlags uint8
		Pad         uint8
		Pad2        uint32
	}
	Pcs [127]uint64
}

// loadPerf_dwarf returns the embedded CollectionSpec for perf_dwarf.
func loadPerf_dwarf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Perf_dwarfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load perf_dwarf: %w", err)
	}

	return spec, err
}

// loadPerf_dwarfObjects loads perf_dwarf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*perf_dwarfObjects
//	*perf_dwarfPrograms
//	*perf_dwarfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPerf_dwarfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPerf_dwarf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// perf_dwarfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfSpecs struct {
	perf_dwarfProgramSpecs
	perf_dwarfMapSpecs
	perf_dwarfVariableSpecs
}

// perf_dwarfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfProgramSpecs struct {
	PerfDwarf *ebpf.ProgramSpec `ebpf:"perf_dwarf"`
}

// perf_dwarfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfMapSpecs struct {
	Pids          *ebpf.MapSpec `ebpf:"pids"`
	StackEvents   *ebpf.MapSpec `ebpf:"stack_events"`
	WalkerScratch *ebpf.MapSpec `ebpf:"walker_scratch"`
}

// perf_dwarfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfVariableSpecs struct {
	SystemWide *ebpf.VariableSpec `ebpf:"system_wide"`
}

// perf_dwarfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfObjects struct {
	perf_dwarfPrograms
	perf_dwarfMaps
	perf_dwarfVariables
}

func (o *perf_dwarfObjects) Close() error {
	return _Perf_dwarfClose(
		&o.perf_dwarfPrograms,
		&o.perf_dwarfMaps,
	)
}

// perf_dwarfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfMaps struct {
	Pids          *ebpf.Map `ebpf:"pids"`
	StackEvents   *ebpf.Map `ebpf:"stack_events"`
	WalkerScratch *ebpf.Map `ebpf:"walker_scratch"`
}

func (m *perf_dwarfMaps) Close() error {
	return _Perf_dwarfClose(
		m.Pids,
		m.StackEvents,
		m.WalkerScratch,
	)
}

// perf_dwarfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfVariables struct {
	SystemWide *ebpf.Variable `ebpf:"system_wide"`
}

// perf_dwarfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfPrograms struct {
	PerfDwarf *ebpf.Program `ebpf:"perf_dwarf"`
}

func (p *perf_dwarfPrograms) Close() error {
	return _Perf_dwarfClose(
		p.PerfDwarf,
	)
}

func _Perf_dwarfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perf_dwarf_x86_bpfel.o
var _Perf_dwarfBytes []byte
