// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package profile

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type perf_dwarfCfiEntry struct {
	_          structs.HostLayout
	PcStart    uint64
	PcEndDelta uint32
	CfaType    uint8
	FpType     uint8
	CfaOffset  int16
	FpOffset   int16
	RaOffset   int16
	RaType     uint8
	Pad        [5]uint8
	_          [6]byte
}

type perf_dwarfCfiMissRatelimitKey struct {
	_       structs.HostLayout
	Pid     uint32
	TableId uint64
}

type perf_dwarfClassification struct {
	_          structs.HostLayout
	PcStart    uint64
	PcEndDelta uint32
	Mode       uint8
	Pad        [3]uint8
}

type perf_dwarfHandoffRange struct {
	_          structs.HostLayout
	Lo         uint64
	Hi         uint64
	UnwinderId uint32
	Pad        uint32
}

type perf_dwarfPidConfig struct {
	_             structs.HostLayout
	Type          uint8
	CollectUser   uint8
	CollectKernel uint8
}

type perf_dwarfPidMapping struct {
	_        structs.HostLayout
	VmaStart uint64
	VmaEnd   uint64
	LoadBias uint64
	TableId  uint64
}

type perf_dwarfSampleRecord struct {
	_   structs.HostLayout
	Hdr struct {
		_           structs.HostLayout
		Pid         uint32
		Tid         uint32
		TimeNs      uint64
		Value       uint64
		Mode        uint8
		N_pcs       uint8
		WalkerFlags uint8
		Pad         uint8
		Pad2        uint32
		KernStack   int64
	}
	Pcs  [127]uint64
	Tags [127]uint8
	_    [1]byte
}

type perf_dwarfWalkPersist struct {
	_               structs.HostLayout
	Pc              uint64
	Fp              uint64
	Sp              uint64
	InterpScratch   [4]uint64
	Pid             uint32
	Tid             uint32
	N_pcs           uint32
	PendingUnwinder uint32
	InterpDone      uint32
	Stopped         uint8
	Pad2            [3]uint8
	TailCalls       uint32
	Pad             uint32
}

// loadPerf_dwarf returns the embedded CollectionSpec for perf_dwarf.
func loadPerf_dwarf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_Perf_dwarfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load perf_dwarf: %w", err)
	}

	return spec, err
}

// loadPerf_dwarfObjects loads perf_dwarf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*perf_dwarfObjects
//	*perf_dwarfPrograms
//	*perf_dwarfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadPerf_dwarfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadPerf_dwarf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// perf_dwarfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfSpecs struct {
	perf_dwarfProgramSpecs
	perf_dwarfMapSpecs
	perf_dwarfVariableSpecs
}

// perf_dwarfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfProgramSpecs struct {
	InterpResumeStep *ebpf.ProgramSpec `ebpf:"interp_resume_step"`
	InterpResumeWalk *ebpf.ProgramSpec `ebpf:"interp_resume_walk"`
	PerfDwarf        *ebpf.ProgramSpec `ebpf:"perf_dwarf"`
}

// perf_dwarfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfMapSpecs struct {
	CfiClassification        *ebpf.MapSpec `ebpf:"cfi_classification"`
	CfiClassificationLengths *ebpf.MapSpec `ebpf:"cfi_classification_lengths"`
	CfiLengths               *ebpf.MapSpec `ebpf:"cfi_lengths"`
	CfiMissEvents            *ebpf.MapSpec `ebpf:"cfi_miss_events"`
	CfiMissRatelimit         *ebpf.MapSpec `ebpf:"cfi_miss_ratelimit"`
	CfiRules                 *ebpf.MapSpec `ebpf:"cfi_rules"`
	HandoffRanges            *ebpf.MapSpec `ebpf:"handoff_ranges"`
	InterpProgs              *ebpf.MapSpec `ebpf:"interp_progs"`
	KernStackmap             *ebpf.MapSpec `ebpf:"kern_stackmap"`
	PidMappingLengths        *ebpf.MapSpec `ebpf:"pid_mapping_lengths"`
	PidMappings              *ebpf.MapSpec `ebpf:"pid_mappings"`
	Pids                     *ebpf.MapSpec `ebpf:"pids"`
	StackEvents              *ebpf.MapSpec `ebpf:"stack_events"`
	WalkStates               *ebpf.MapSpec `ebpf:"walk_states"`
	WalkerScratch            *ebpf.MapSpec `ebpf:"walker_scratch"`
}

// perf_dwarfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type perf_dwarfVariableSpecs struct {
	BtfAnchorCfiEntry       *ebpf.VariableSpec `ebpf:"_btf_anchor_cfi_entry"`
	BtfAnchorClassification *ebpf.VariableSpec `ebpf:"_btf_anchor_classification"`
	BtfAnchorPidMapping     *ebpf.VariableSpec `ebpf:"_btf_anchor_pid_mapping"`
	InterpEnabled           *ebpf.VariableSpec `ebpf:"interp_enabled"`
	KernelStacksEnabled     *ebpf.VariableSpec `ebpf:"kernel_stacks_enabled"`
	SystemWide              *ebpf.VariableSpec `ebpf:"system_wide"`
}

// perf_dwarfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfObjects struct {
	perf_dwarfPrograms
	perf_dwarfMaps
	perf_dwarfVariables
}

func (o *perf_dwarfObjects) Close() error {
	return _Perf_dwarfClose(
		&o.perf_dwarfPrograms,
		&o.perf_dwarfMaps,
	)
}

// perf_dwarfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfMaps struct {
	CfiClassification        *ebpf.Map `ebpf:"cfi_classification"`
	CfiClassificationLengths *ebpf.Map `ebpf:"cfi_classification_lengths"`
	CfiLengths               *ebpf.Map `ebpf:"cfi_lengths"`
	CfiMissEvents            *ebpf.Map `ebpf:"cfi_miss_events"`
	CfiMissRatelimit         *ebpf.Map `ebpf:"cfi_miss_ratelimit"`
	CfiRules                 *ebpf.Map `ebpf:"cfi_rules"`
	HandoffRanges            *ebpf.Map `ebpf:"handoff_ranges"`
	InterpProgs              *ebpf.Map `ebpf:"interp_progs"`
	KernStackmap             *ebpf.Map `ebpf:"kern_stackmap"`
	PidMappingLengths        *ebpf.Map `ebpf:"pid_mapping_lengths"`
	PidMappings              *ebpf.Map `ebpf:"pid_mappings"`
	Pids                     *ebpf.Map `ebpf:"pids"`
	StackEvents              *ebpf.Map `ebpf:"stack_events"`
	WalkStates               *ebpf.Map `ebpf:"walk_states"`
	WalkerScratch            *ebpf.Map `ebpf:"walker_scratch"`
}

func (m *perf_dwarfMaps) Close() error {
	return _Perf_dwarfClose(
		m.CfiClassification,
		m.CfiClassificationLengths,
		m.CfiLengths,
		m.CfiMissEvents,
		m.CfiMissRatelimit,
		m.CfiRules,
		m.HandoffRanges,
		m.InterpProgs,
		m.KernStackmap,
		m.PidMappingLengths,
		m.PidMappings,
		m.Pids,
		m.StackEvents,
		m.WalkStates,
		m.WalkerScratch,
	)
}

// perf_dwarfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfVariables struct {
	BtfAnchorCfiEntry       *ebpf.Variable `ebpf:"_btf_anchor_cfi_entry"`
	BtfAnchorClassification *ebpf.Variable `ebpf:"_btf_anchor_classification"`
	BtfAnchorPidMapping     *ebpf.Variable `ebpf:"_btf_anchor_pid_mapping"`
	InterpEnabled           *ebpf.Variable `ebpf:"interp_enabled"`
	KernelStacksEnabled     *ebpf.Variable `ebpf:"kernel_stacks_enabled"`
	SystemWide              *ebpf.Variable `ebpf:"system_wide"`
}

// perf_dwarfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadPerf_dwarfObjects or ebpf.CollectionSpec.LoadAndAssign.
type perf_dwarfPrograms struct {
	InterpResumeStep *ebpf.Program `ebpf:"interp_resume_step"`
	InterpResumeWalk *ebpf.Program `ebpf:"interp_resume_walk"`
	PerfDwarf        *ebpf.Program `ebpf:"perf_dwarf"`
}

func (p *perf_dwarfPrograms) Close() error {
	return _Perf_dwarfClose(
		p.InterpResumeStep,
		p.InterpResumeWalk,
		p.PerfDwarf,
	)
}

func _Perf_dwarfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed perf_dwarf_arm64_bpfel.o
var _Perf_dwarfBytes []byte
