// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadCPU returns the embedded CollectionSpec for CPU.
func LoadCPU() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CPUBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CPU: %w", err)
	}

	return spec, err
}

// LoadCPUObjects loads CPU and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CPUObjects
//	*CPUPrograms
//	*CPUMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCPUObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCPU()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CPUSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CPUSpecs struct {
	CPUProgramSpecs
	CPUMapSpecs
}

// CPUSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CPUProgramSpecs struct {
	HandleSwitch    *ebpf.ProgramSpec `ebpf:"handle_switch"`
	OnKcpustatFetch *ebpf.ProgramSpec `ebpf:"on_kcpustat_fetch"`
}

// CPUMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CPUMapSpecs struct {
	LastSeen  *ebpf.MapSpec `ebpf:"last_seen"`
	PidFilter *ebpf.MapSpec `ebpf:"pid_filter"`
	Rb        *ebpf.MapSpec `ebpf:"rb"`
}

// CPUObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCPUObjects or ebpf.CollectionSpec.LoadAndAssign.
type CPUObjects struct {
	CPUPrograms
	CPUMaps
}

func (o *CPUObjects) Close() error {
	return _CPUClose(
		&o.CPUPrograms,
		&o.CPUMaps,
	)
}

// CPUMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCPUObjects or ebpf.CollectionSpec.LoadAndAssign.
type CPUMaps struct {
	LastSeen  *ebpf.Map `ebpf:"last_seen"`
	PidFilter *ebpf.Map `ebpf:"pid_filter"`
	Rb        *ebpf.Map `ebpf:"rb"`
}

func (m *CPUMaps) Close() error {
	return _CPUClose(
		m.LastSeen,
		m.PidFilter,
		m.Rb,
	)
}

// CPUPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCPUObjects or ebpf.CollectionSpec.LoadAndAssign.
type CPUPrograms struct {
	HandleSwitch    *ebpf.Program `ebpf:"handle_switch"`
	OnKcpustatFetch *ebpf.Program `ebpf:"on_kcpustat_fetch"`
}

func (p *CPUPrograms) Close() error {
	return _CPUClose(
		p.HandleSwitch,
		p.OnKcpustatFetch,
	)
}

func _CPUClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpu_x86_bpfel.o
var _CPUBytes []byte
