// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package cpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadCPU returns the embedded CollectionSpec for CPU.
func LoadCPU() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CPUBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CPU: %w", err)
	}

	return spec, err
}

// LoadCPUObjects loads CPU and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CPUObjects
//	*CPUPrograms
//	*CPUMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCPUObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCPU()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CPUSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CPUSpecs struct {
	CPUProgramSpecs
	CPUMapSpecs
}

// CPUSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CPUProgramSpecs struct {
	HandleSwitch *ebpf.ProgramSpec `ebpf:"handle_switch"`
}

// CPUMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CPUMapSpecs struct {
	CacheMissesReader     *ebpf.MapSpec `ebpf:"cache_misses_reader"`
	CpuCyclesReader       *ebpf.MapSpec `ebpf:"cpu_cycles_reader"`
	CpuInstructionsReader *ebpf.MapSpec `ebpf:"cpu_instructions_reader"`
	HwCountersEnabled     *ebpf.MapSpec `ebpf:"hw_counters_enabled"`
	LastSeen              *ebpf.MapSpec `ebpf:"last_seen"`
	PidFilter             *ebpf.MapSpec `ebpf:"pid_filter"`
	PrevCacheMisses       *ebpf.MapSpec `ebpf:"prev_cache_misses"`
	PrevCycles            *ebpf.MapSpec `ebpf:"prev_cycles"`
	PrevInstructions      *ebpf.MapSpec `ebpf:"prev_instructions"`
	Rb                    *ebpf.MapSpec `ebpf:"rb"`
}

// CPUObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCPUObjects or ebpf.CollectionSpec.LoadAndAssign.
type CPUObjects struct {
	CPUPrograms
	CPUMaps
}

func (o *CPUObjects) Close() error {
	return _CPUClose(
		&o.CPUPrograms,
		&o.CPUMaps,
	)
}

// CPUMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCPUObjects or ebpf.CollectionSpec.LoadAndAssign.
type CPUMaps struct {
	CacheMissesReader     *ebpf.Map `ebpf:"cache_misses_reader"`
	CpuCyclesReader       *ebpf.Map `ebpf:"cpu_cycles_reader"`
	CpuInstructionsReader *ebpf.Map `ebpf:"cpu_instructions_reader"`
	HwCountersEnabled     *ebpf.Map `ebpf:"hw_counters_enabled"`
	LastSeen              *ebpf.Map `ebpf:"last_seen"`
	PidFilter             *ebpf.Map `ebpf:"pid_filter"`
	PrevCacheMisses       *ebpf.Map `ebpf:"prev_cache_misses"`
	PrevCycles            *ebpf.Map `ebpf:"prev_cycles"`
	PrevInstructions      *ebpf.Map `ebpf:"prev_instructions"`
	Rb                    *ebpf.Map `ebpf:"rb"`
}

func (m *CPUMaps) Close() error {
	return _CPUClose(
		m.CacheMissesReader,
		m.CpuCyclesReader,
		m.CpuInstructionsReader,
		m.HwCountersEnabled,
		m.LastSeen,
		m.PidFilter,
		m.PrevCacheMisses,
		m.PrevCycles,
		m.PrevInstructions,
		m.Rb,
	)
}

// CPUPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCPUObjects or ebpf.CollectionSpec.LoadAndAssign.
type CPUPrograms struct {
	HandleSwitch *ebpf.Program `ebpf:"handle_switch"`
}

func (p *CPUPrograms) Close() error {
	return _CPUClose(
		p.HandleSwitch,
	)
}

func _CPUClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpu_arm64_bpfel.o
var _CPUBytes []byte
