// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package cpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCpu returns the embedded CollectionSpec for cpu.
func loadCpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cpu: %w", err)
	}

	return spec, err
}

// loadCpuObjects loads cpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cpuObjects
//	*cpuPrograms
//	*cpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuSpecs struct {
	cpuProgramSpecs
	cpuMapSpecs
}

// cpuSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuProgramSpecs struct {
	HandleSwitch *ebpf.ProgramSpec `ebpf:"handle_switch"`
}

// cpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cpuMapSpecs struct {
	CacheMissesReader     *ebpf.MapSpec `ebpf:"cache_misses_reader"`
	CpuCyclesReader       *ebpf.MapSpec `ebpf:"cpu_cycles_reader"`
	CpuInstructionsReader *ebpf.MapSpec `ebpf:"cpu_instructions_reader"`
	HwCountersEnabled     *ebpf.MapSpec `ebpf:"hw_counters_enabled"`
	LastSeen              *ebpf.MapSpec `ebpf:"last_seen"`
	PidFilter             *ebpf.MapSpec `ebpf:"pid_filter"`
	PrevCacheMisses       *ebpf.MapSpec `ebpf:"prev_cache_misses"`
	PrevCycles            *ebpf.MapSpec `ebpf:"prev_cycles"`
	PrevInstructions      *ebpf.MapSpec `ebpf:"prev_instructions"`
	Rb                    *ebpf.MapSpec `ebpf:"rb"`
}

// cpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuObjects struct {
	cpuPrograms
	cpuMaps
}

func (o *cpuObjects) Close() error {
	return _CpuClose(
		&o.cpuPrograms,
		&o.cpuMaps,
	)
}

// cpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuMaps struct {
	CacheMissesReader     *ebpf.Map `ebpf:"cache_misses_reader"`
	CpuCyclesReader       *ebpf.Map `ebpf:"cpu_cycles_reader"`
	CpuInstructionsReader *ebpf.Map `ebpf:"cpu_instructions_reader"`
	HwCountersEnabled     *ebpf.Map `ebpf:"hw_counters_enabled"`
	LastSeen              *ebpf.Map `ebpf:"last_seen"`
	PidFilter             *ebpf.Map `ebpf:"pid_filter"`
	PrevCacheMisses       *ebpf.Map `ebpf:"prev_cache_misses"`
	PrevCycles            *ebpf.Map `ebpf:"prev_cycles"`
	PrevInstructions      *ebpf.Map `ebpf:"prev_instructions"`
	Rb                    *ebpf.Map `ebpf:"rb"`
}

func (m *cpuMaps) Close() error {
	return _CpuClose(
		m.CacheMissesReader,
		m.CpuCyclesReader,
		m.CpuInstructionsReader,
		m.HwCountersEnabled,
		m.LastSeen,
		m.PidFilter,
		m.PrevCacheMisses,
		m.PrevCycles,
		m.PrevInstructions,
		m.Rb,
	)
}

// cpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type cpuPrograms struct {
	HandleSwitch *ebpf.Program `ebpf:"handle_switch"`
}

func (p *cpuPrograms) Close() error {
	return _CpuClose(
		p.HandleSwitch,
	)
}

func _CpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpu_x86_bpfel.o
var _CpuBytes []byte
