// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package offcpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type offcpuOffcpuKey struct {
	Pid       uint32
	_         [4]byte
	KernStack int64
	UserStack int64
}

type offcpuStartKey struct {
	Pid  uint32
	Tgid uint32
}

type offcpuStartVal struct {
	Timestamp uint64
	KernStack int64
	UserStack int64
}

// loadOffcpu returns the embedded CollectionSpec for offcpu.
func loadOffcpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OffcpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load offcpu: %w", err)
	}

	return spec, err
}

// loadOffcpuObjects loads offcpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*offcpuObjects
//	*offcpuPrograms
//	*offcpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadOffcpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadOffcpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// offcpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuSpecs struct {
	offcpuProgramSpecs
	offcpuMapSpecs
}

// offcpuSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuProgramSpecs struct {
	OffcpuSchedSwitch *ebpf.ProgramSpec `ebpf:"offcpu_sched_switch"`
}

// offcpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type offcpuMapSpecs struct {
	OffcpuCounts *ebpf.MapSpec `ebpf:"offcpu_counts"`
	PidFilter    *ebpf.MapSpec `ebpf:"pid_filter"`
	Stackmap     *ebpf.MapSpec `ebpf:"stackmap"`
	Start        *ebpf.MapSpec `ebpf:"start"`
}

// offcpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuObjects struct {
	offcpuPrograms
	offcpuMaps
}

func (o *offcpuObjects) Close() error {
	return _OffcpuClose(
		&o.offcpuPrograms,
		&o.offcpuMaps,
	)
}

// offcpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuMaps struct {
	OffcpuCounts *ebpf.Map `ebpf:"offcpu_counts"`
	PidFilter    *ebpf.Map `ebpf:"pid_filter"`
	Stackmap     *ebpf.Map `ebpf:"stackmap"`
	Start        *ebpf.Map `ebpf:"start"`
}

func (m *offcpuMaps) Close() error {
	return _OffcpuClose(
		m.OffcpuCounts,
		m.PidFilter,
		m.Stackmap,
		m.Start,
	)
}

// offcpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type offcpuPrograms struct {
	OffcpuSchedSwitch *ebpf.Program `ebpf:"offcpu_sched_switch"`
}

func (p *offcpuPrograms) Close() error {
	return _OffcpuClose(
		p.OffcpuSchedSwitch,
	)
}

func _OffcpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed offcpu_arm64_bpfel.o
var _OffcpuBytes []byte
