// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package offcpu

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type OffcpuOffcpuKey struct {
	Pid       uint32
	_         [4]byte
	KernStack int64
	UserStack int64
}

type OffcpuStartKey struct {
	Pid  uint32
	Tgid uint32
}

type OffcpuStartVal struct {
	Timestamp uint64
	KernStack int64
	UserStack int64
}

// LoadOffcpu returns the embedded CollectionSpec for Offcpu.
func LoadOffcpu() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OffcpuBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Offcpu: %w", err)
	}

	return spec, err
}

// LoadOffcpuObjects loads Offcpu and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OffcpuObjects
//	*OffcpuPrograms
//	*OffcpuMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOffcpuObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOffcpu()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OffcpuSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuSpecs struct {
	OffcpuProgramSpecs
	OffcpuMapSpecs
}

// OffcpuSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuProgramSpecs struct {
	OffcpuSchedSwitch *ebpf.ProgramSpec `ebpf:"offcpu_sched_switch"`
}

// OffcpuMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuMapSpecs struct {
	OffcpuCounts *ebpf.MapSpec `ebpf:"offcpu_counts"`
	PidFilter    *ebpf.MapSpec `ebpf:"pid_filter"`
	Stackmap     *ebpf.MapSpec `ebpf:"stackmap"`
	Start        *ebpf.MapSpec `ebpf:"start"`
}

// OffcpuObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuObjects struct {
	OffcpuPrograms
	OffcpuMaps
}

func (o *OffcpuObjects) Close() error {
	return _OffcpuClose(
		&o.OffcpuPrograms,
		&o.OffcpuMaps,
	)
}

// OffcpuMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuMaps struct {
	OffcpuCounts *ebpf.Map `ebpf:"offcpu_counts"`
	PidFilter    *ebpf.Map `ebpf:"pid_filter"`
	Stackmap     *ebpf.Map `ebpf:"stackmap"`
	Start        *ebpf.Map `ebpf:"start"`
}

func (m *OffcpuMaps) Close() error {
	return _OffcpuClose(
		m.OffcpuCounts,
		m.PidFilter,
		m.Stackmap,
		m.Start,
	)
}

// OffcpuPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuPrograms struct {
	OffcpuSchedSwitch *ebpf.Program `ebpf:"offcpu_sched_switch"`
}

func (p *OffcpuPrograms) Close() error {
	return _OffcpuClose(
		p.OffcpuSchedSwitch,
	)
}

func _OffcpuClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed offcpu_bpfeb.o
var _OffcpuBytes []byte
