// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package hip

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadHiplaunch returns the embedded CollectionSpec for hiplaunch.
func loadHiplaunch() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HiplaunchBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load hiplaunch: %w", err)
	}

	return spec, err
}

// loadHiplaunchObjects loads hiplaunch and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*hiplaunchObjects
//	*hiplaunchPrograms
//	*hiplaunchMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHiplaunchObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHiplaunch()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// hiplaunchSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hiplaunchSpecs struct {
	hiplaunchProgramSpecs
	hiplaunchMapSpecs
	hiplaunchVariableSpecs
}

// hiplaunchProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hiplaunchProgramSpecs struct {
	HandleHipLaunch *ebpf.ProgramSpec `ebpf:"handle_hip_launch"`
}

// hiplaunchMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hiplaunchMapSpecs struct {
	Events   *ebpf.MapSpec `ebpf:"events"`
	Stackmap *ebpf.MapSpec `ebpf:"stackmap"`
}

// hiplaunchVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type hiplaunchVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// hiplaunchObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHiplaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type hiplaunchObjects struct {
	hiplaunchPrograms
	hiplaunchMaps
	hiplaunchVariables
}

func (o *hiplaunchObjects) Close() error {
	return _HiplaunchClose(
		&o.hiplaunchPrograms,
		&o.hiplaunchMaps,
	)
}

// hiplaunchMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHiplaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type hiplaunchMaps struct {
	Events   *ebpf.Map `ebpf:"events"`
	Stackmap *ebpf.Map `ebpf:"stackmap"`
}

func (m *hiplaunchMaps) Close() error {
	return _HiplaunchClose(
		m.Events,
		m.Stackmap,
	)
}

// hiplaunchVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHiplaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type hiplaunchVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// hiplaunchPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHiplaunchObjects or ebpf.CollectionSpec.LoadAndAssign.
type hiplaunchPrograms struct {
	HandleHipLaunch *ebpf.Program `ebpf:"handle_hip_launch"`
}

func (p *hiplaunchPrograms) Close() error {
	return _HiplaunchClose(
		p.HandleHipLaunch,
	)
}

func _HiplaunchClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed hiplaunch_x86_bpfel.o
var _HiplaunchBytes []byte
