// perf-dwarf-test is a diagnostic for the perf_dwarf.bpf.c program (S2).
// Given a PID, it loads the BPF program, attaches it to per-CPU perf events
// at the target frequency, and prints each sample record consumed from the
// stack_events ringbuf. No symbolization — raw PCs only; correctness is
// judged by comparing the chain shape against the pure-Go fpwalker.
package main

import (
	"encoding/binary"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"runtime"
	"syscall"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"golang.org/x/sys/unix"

	"github.com/dpsoft/perf-agent/profile"
	"github.com/dpsoft/perf-agent/unwind/ehcompile"
	"github.com/dpsoft/perf-agent/unwind/ehmaps"
)

const (
	maxFrames        = 127
	sampleHeaderSize = 32
	sampleRecordSize = sampleHeaderSize + maxFrames*8
)

// perfDwarfObjects / loadPerfDwarfObjects are generated by bpf2go inside
// the profile package with name-mangled identifiers. We reflect the ones
// we need through a thin local wrapper so main doesn't need to know the
// generator's specific spelling.
func loadObjects() (*loadedObjects, error) {
	return profile.LoadPerfDwarf()
}

type loadedObjects = profile.PerfDwarf

func main() {
	pid := flag.Int("pid", 0, "target PID (required)")
	freq := flag.Uint64("freq", 99, "sample frequency Hz")
	duration := flag.Int("duration", 10, "max seconds to sample")
	limit := flag.Int("limit", 10, "max samples to print")
	targetBin := flag.String("target-binary", "", "path to the PID's main executable (enables DWARF unwinding)")
	flag.Parse()

	if *pid == 0 {
		fmt.Fprintln(os.Stderr, "usage: perf-dwarf-test --pid <N> [--freq 99] [--duration 10] [--limit 10] [--target-binary /path/to/bin]")
		os.Exit(2)
	}

	objs, err := loadObjects()
	if err != nil {
		log.Fatalf("load BPF: %v", err)
	}
	defer objs.Close()

	// Configure targeted mode: system_wide=false, insert the PID.
	if err := objs.SetSystemWide(false); err != nil {
		log.Fatalf("set system_wide: %v", err)
	}
	if err := objs.AddPID(uint32(*pid)); err != nil {
		log.Fatalf("add PID: %v", err)
	}

	if *targetBin != "" {
		if err := populateDwarfMaps(objs, uint32(*pid), *targetBin); err != nil {
			log.Fatalf("populate dwarf maps: %v", err)
		}
		fmt.Printf("installed CFI for %s\n", *targetBin)
	}

	// Per-CPU perf events.
	ncpu := runtime.NumCPU()
	perfFDs := make([]int, 0, ncpu)
	perfLinks := make([]link.Link, 0, ncpu)
	defer func() {
		for _, l := range perfLinks {
			_ = l.Close()
		}
		for _, fd := range perfFDs {
			_ = unix.Close(fd)
		}
	}()

	attr := &unix.PerfEventAttr{
		Type:   unix.PERF_TYPE_SOFTWARE,
		Config: unix.PERF_COUNT_SW_CPU_CLOCK,
		Size:   uint32(unsafe.Sizeof(unix.PerfEventAttr{})),
		Sample: *freq,
		Bits:   unix.PerfBitFreq | unix.PerfBitDisabled,
	}
	for cpu := 0; cpu < ncpu; cpu++ {
		// pid=-1, cpu=N samples all threads on that CPU; BPF-side pids map
		// (populated via AddPID above) filters to our target's TGID. Using
		// pid=*pid here would sample only that specific TID, missing worker
		// threads where most real workloads' CPU time lives.
		fd, err := unix.PerfEventOpen(attr, -1, cpu, -1, unix.PERF_FLAG_FD_CLOEXEC)
		if err != nil {
			if errors.Is(err, syscall.ESRCH) {
				log.Printf("CPU %d: target PID vanished or not runnable here; skipping", cpu)
				continue
			}
			log.Fatalf("perf_event_open cpu=%d: %v", cpu, err)
		}
		perfFDs = append(perfFDs, fd)

		rl, err := link.AttachRawLink(link.RawLinkOptions{
			Target:  fd,
			Program: objs.Program(),
			Attach:  ebpf.AttachPerfEvent,
		})
		if err != nil {
			log.Fatalf("attach BPF to perf event cpu=%d: %v", cpu, err)
		}
		perfLinks = append(perfLinks, rl)

		if err := unix.IoctlSetInt(fd, unix.PERF_EVENT_IOC_ENABLE, 0); err != nil {
			log.Fatalf("enable perf event cpu=%d: %v", cpu, err)
		}
	}
	if len(perfFDs) == 0 {
		log.Fatalf("no perf events attached — PID %d may have exited or never been scheduled", *pid)
	}

	// Ringbuf consumer.
	rd, err := ringbuf.NewReader(objs.RingbufMap())
	if err != nil {
		log.Fatalf("ringbuf reader: %v", err)
	}
	defer rd.Close()

	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGINT, syscall.SIGTERM)

	fmt.Printf("perf-dwarf-test: pid=%d freq=%dHz duration=%ds limit=%d cpus=%d\n",
		*pid, *freq, *duration, *limit, len(perfFDs))
	fmt.Println("sampling…")

	deadline := time.Now().Add(time.Duration(*duration) * time.Second)
	count := 0
loop:
	for count < *limit && time.Now().Before(deadline) {
		select {
		case <-sig:
			break loop
		default:
		}
		rd.SetDeadline(time.Now().Add(500 * time.Millisecond))
		rec, err := rd.Read()
		if err != nil {
			if errors.Is(err, os.ErrDeadlineExceeded) {
				continue
			}
			log.Printf("ringbuf read: %v", err)
			break
		}
		count++
		printRecord(count, rec.RawSample)
	}
	fmt.Printf("\n[done: %d samples consumed]\n", count)
}

// printRecord parses the fixed-size sample_record and renders a summary.
func printRecord(n int, raw []byte) {
	if len(raw) < sampleHeaderSize {
		fmt.Printf("--- sample #%d --- (truncated: %d bytes)\n", n, len(raw))
		return
	}
	pid := binary.LittleEndian.Uint32(raw[0:4])
	tid := binary.LittleEndian.Uint32(raw[4:8])
	timeNs := binary.LittleEndian.Uint64(raw[8:16])
	value := binary.LittleEndian.Uint64(raw[16:24])
	mode := raw[24]
	nPCs := int(raw[25])
	walkerFlags := raw[26]

	if nPCs > maxFrames {
		nPCs = maxFrames
	}

	fmt.Printf("--- sample #%d ---\n", n)
	fmt.Printf("  pid/tid   : %d/%d\n", pid, tid)
	fmt.Printf("  time_ns   : %d\n", timeNs)
	fmt.Printf("  value     : %d\n", value)
	fmt.Printf("  mode      : %d (0=FP_SAFE 1=FP_LESS 2=FALLBACK)\n", mode)
	fmt.Printf("  walker_fl : 0x%x\n", walkerFlags)
	fmt.Printf("  chain (%d frames):\n", nPCs)

	pcsStart := sampleHeaderSize
	for i := 0; i < nPCs; i++ {
		off := pcsStart + i*8
		if off+8 > len(raw) {
			break
		}
		pc := binary.LittleEndian.Uint64(raw[off : off+8])
		fmt.Printf("    [%02d] 0x%016x\n", i, pc)
	}
	fmt.Println()
}

// populateDwarfMaps runs ehcompile on binPath and installs CFI,
// classification, and pid_mappings into the BPF maps for the given PID.
func populateDwarfMaps(objs *profile.PerfDwarf, pid uint32, binPath string) error {
	entries, classifications, err := ehcompile.Compile(binPath)
	if err != nil {
		return fmt.Errorf("ehcompile: %w", err)
	}
	buildID, err := ehmaps.ReadBuildID(binPath)
	if err != nil {
		return fmt.Errorf("build-id: %w", err)
	}
	tableID := ehmaps.TableIDForBuildID(buildID)

	if err := ehmaps.PopulateCFI(ehmaps.PopulateCFIArgs{
		TableID: tableID, Entries: entries,
		OuterMap: objs.CFIRulesMap(), LengthMap: objs.CFILengthsMap(),
	}); err != nil {
		return err
	}
	if err := ehmaps.PopulateClassification(ehmaps.PopulateClassificationArgs{
		TableID: tableID, Entries: classifications,
		OuterMap: objs.CFIClassificationMap(), LengthMap: objs.CFIClassificationLengthsMap(),
	}); err != nil {
		return err
	}
	mappings, err := ehmaps.LoadProcessMappings(int(pid), binPath, tableID)
	if err != nil {
		return err
	}
	return ehmaps.PopulatePIDMappings(ehmaps.PopulatePIDMappingsArgs{
		PID: pid, Mappings: mappings,
		OuterMap: objs.PIDMappingsMap(), LengthMap: objs.PIDMappingLengthsMap(),
	})
}



