// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package gpuprobe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadGpuusdt returns the embedded CollectionSpec for gpuusdt.
func loadGpuusdt() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_GpuusdtBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load gpuusdt: %w", err)
	}

	return spec, err
}

// loadGpuusdtObjects loads gpuusdt and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*gpuusdtObjects
//	*gpuusdtPrograms
//	*gpuusdtMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadGpuusdtObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadGpuusdt()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// gpuusdtSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gpuusdtSpecs struct {
	gpuusdtProgramSpecs
	gpuusdtMapSpecs
	gpuusdtVariableSpecs
}

// gpuusdtProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gpuusdtProgramSpecs struct {
	GpuUsdtBatch *ebpf.ProgramSpec `ebpf:"gpu_usdt_batch"`
}

// gpuusdtMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gpuusdtMapSpecs struct {
	Dropped *ebpf.MapSpec `ebpf:"dropped"`
	Events  *ebpf.MapSpec `ebpf:"events"`
}

// gpuusdtVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type gpuusdtVariableSpecs struct {
}

// gpuusdtObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadGpuusdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type gpuusdtObjects struct {
	gpuusdtPrograms
	gpuusdtMaps
	gpuusdtVariables
}

func (o *gpuusdtObjects) Close() error {
	return _GpuusdtClose(
		&o.gpuusdtPrograms,
		&o.gpuusdtMaps,
	)
}

// gpuusdtMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadGpuusdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type gpuusdtMaps struct {
	Dropped *ebpf.Map `ebpf:"dropped"`
	Events  *ebpf.Map `ebpf:"events"`
}

func (m *gpuusdtMaps) Close() error {
	return _GpuusdtClose(
		m.Dropped,
		m.Events,
	)
}

// gpuusdtVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadGpuusdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type gpuusdtVariables struct {
}

// gpuusdtPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadGpuusdtObjects or ebpf.CollectionSpec.LoadAndAssign.
type gpuusdtPrograms struct {
	GpuUsdtBatch *ebpf.Program `ebpf:"gpu_usdt_batch"`
}

func (p *gpuusdtPrograms) Close() error {
	return _GpuusdtClose(
		p.GpuUsdtBatch,
	)
}

func _GpuusdtClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed gpuusdt_arm64_bpfel.o
var _GpuusdtBytes []byte
